{% set name = "rdchiral_cpp" %}
{% set version = "1.1.3" %}
{% set git_version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/ljn917/rdchiral_cpp/-/archive/{{ git_version }}/rdchiral_cpp-{{ git_version }}.tar.gz
  sha256: 09f71f7b3c16eb15452226908b66d57b9a779886053adc801e638cd643fdfaa5

build:
  number: 3
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
    - pkg-config
  host:
    - python
    - pip
    - rdkit {{ rdkit_version }}
    - libboost-python-devel
  run:
    - python
    - {{ pin_compatible('rdkit', max_pin='x.x') }}

test:
  imports:
    - rdchiral
  source_files:
    - test/test_rdchiral.py
    - test/test_rdchiral_cases.json
    - test/test_rdchiral2.py
    - test/test_rdchiral3.py
    - test/test_rdchiral4.py
  commands:
    - python test/test_rdchiral.py
    - python test/test_rdchiral3.py
    - python test/test_rdchiral4.py

about:
  home: https://gitlab.com/ljn917/rdchiral_cpp
  license: MIT
  license_file: LICENSE
  summary: 'C++ implementation of rdchiral'

extra:
  recipe-maintainers:
    - ljn917
    - hadim
