# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      osx_64_python3.10.____cpythonpython_version3.10._rdkit_version2022.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.10._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.10._rdkit_version2022.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.10._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.11._rdkit_version2022.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.11._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.6._rdkit_version2020.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.6._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.6._rdkit_version2021.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.6._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2020.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2021.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2021.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2022.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.7._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2020.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2021.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2021.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2022.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2022.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.8._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2020.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2021.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2021.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2022.03._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2022.09._:
        CONFIG: osx_64_python3.10.____cpythonpython_version3.9._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.10._rdkit_version2022.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.10._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.10._rdkit_version2022.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.10._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.11._rdkit_version2022.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.11._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.6._rdkit_version2020.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.6._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.6._rdkit_version2021.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.6._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2020.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2021.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2021.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2022.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.7._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2020.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2021.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2021.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2022.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2022.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.8._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2020.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2021.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2021.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2022.03._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2022.09._:
        CONFIG: osx_64_python3.8.____cpythonpython_version3.9._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.10._rdkit_version2022.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.10._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.10._rdkit_version2022.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.10._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.11._rdkit_version2022.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.11._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.6._rdkit_version2020.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.6._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.6._rdkit_version2021.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.6._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2020.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2021.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2021.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2022.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.7._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2020.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2021.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2021.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2022.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2022.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.8._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2020.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2020.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2021.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2021.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2021.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2021.09._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2022.03._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2022.03._
        UPLOAD_PACKAGES: 'True'
      osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2022.09._:
        CONFIG: osx_64_python3.9.____cpythonpython_version3.9._rdkit_version2022.09._
        UPLOAD_PACKAGES: 'True'
    maxParallel: 25
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)